
[gcp_service_account]
type = "service_account"
project_id = "walkwithgodapp"
private_key_id = "2091d86141ddfa71b678c3e6da30dcacd32dc9cf"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDL8ScX0ea4WUkr
mi7EmUlgyhHd3N2s5LsfVOwi33yfks1ch/LPKIbSRf8d37bF0ySnm6HKDvjVGQj+
4ZemhhSV4TpzOtYm8eYdeWPFrkO251D+vLBcrQAdzrcIxnT98UZ75+8eDWQv0fD4
cuUyNVFMQPDsYMFicdnz59KO/TMqijjeHDb8+NvuVJbLOx12512VvCQteo3PdKWl
SQvfXyy0bcSfpbsiltANgk46xbswWckWOiPDZU82olGTpKo7d0RfTF2OK2dIuM6o
8v+yLQmjU6fJfEqWbnyP0ZHxKInh005ylXzbTyz8J8xqZs7iImt6e2fxklcMoz0y
LMh05HgRAgMBAAECggEAE21//P7JyPS3edP8oc2c7f+d61nRk7lv4nSVcJ6D2ZMz
ZT3NqYKZslEI9Cx2NbrvFljm9Q/PUESL5PTyXIKQFjWQGv9HPItFcbgZQzD+Qh+f
yX6J2fBAjzZcnRVDupe4EFBoSN97dGs+VnqifxGRcq9KjCgM8A76tWeXeTfhXotE
AculLYAOfogxhgR+UPaSDkt33WCpCkymcGs16POhwPixakMHguPj4qGoGFTf97oR
WOhqBvwGyFOWNTCI/yHvw4IH4QZ6A/NGs6HG/nPRbv2aCTcb3sg1JfjNzF2HQM4Y
txCl719BfIJY/TzLAdIZv/VYjcJO2ZzjIR6U1dpr6QKBgQDrAsqZurezfOq1EGeB
uPfdZtgubS/Wejrhow8qWL0t29/CXHq5R+FfPI7fvjbiOtX9LxjdWEFpyEW0GVDp
QGF/lDwJlmMLTUrkeqnA4XTdH9m0p3nQ4C5nwGT91QWOOQpFS9hyGGnYLo/DQ5Eq
aTEBWiqtS/WipdJwKgHAukvXuQKBgQDeKAM6oBR5D4BHTRDDmHYmhAF+EuVHK5PA
eBwRKC0CfwryH6Osj9e0XGmlKDeDzXodwqKNK/7KgHx8Jl1HpmrX25T2scHJXHNr
KTe8dK5RG7TU/HlLYsAfYdhW0iJ50s+6oALzW1hQvOQgO+zbUTW0po1IavMiRI5v
OOI+K8UfGQKBgAeiapR95VPWXgWNx98F9D9kBOfVMjWkeN81nduBUHv55ZX5zR7R
v/eJDxcjpcLJqIP2ELe4Ez/tep40KFW7eq9bUGv7T7JhS2qKtZMHf/VjAH6G5kUr
0zYZoO5CClEpdzTzFs/2DRIxyQfN3RxkmGvz0ukYS52CB4kPRElPhAE5AoGALh/y
o65u8b+1K5ilnWa/STnpMWrs7bzvfWuysCE+TyFffWvySLbI22rAiIj0FcqIyzsJ
EvSKfzL0Jba1cVXtIwo1QI8hpBQs5pf1OYykULTG893DtVI4f4uKJmSUweRyOtZU
JoDVslW1q7elctfGpc5a0Slbd8byJ8eQucXOtKkCgYEApdmh19Sq3awHiqk8VtOZ
8w04OA//nkSJCcQ430dER/fHrxQC/C79lLCfn+EKABadyWNdCRJQqaiJdSzOT662
Idqof5FI2cNUmi0ZVqkUq5TkNvmOLdbdju6G0p8RHoWz3RP4ubvEcuchHZkdtWUt
bM0kRNp7YOiwKDtcVFS+KEE=
-----END PRIVATE KEY-----
"""
client_email = "prayer-request-service@walkwithgodapp.iam.gserviceaccount.com"
client_id = "102810568684052458837"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/prayer-request-service%40walkwithgodapp.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
